### ISSUE TITLE
In data(model_M4) : data set ‘model_M4’ not found

### ISSUE THREAD

**Issue by Joelmamarques** [andybega/M4metaresults.lite#1]
Hi,
I've installed the M4metaresults.lite package. But, when I use the comand: data(model_M4), I receive the message: 

**data set ‘model_M4’ not found.**

Any help will be apreciate.

Joelma Marques
Master Student

**Comment by andybega** [comment]
Hello,

could you try installing the package again?

You'll need to install M4metalearning first, see https://github.com/pmontman/M4metaresults.

If it still doesn't work, have you tried installing the original package from https://github.com/pmontman/M4metaresults/releases?

**Comment by Joelmamarques** [comment]
Thank you Andy! I've had to improve the RAM memory of my notebook and now the problem is solved.

Andy, could you please help me with one more question? What is the difference between OWA and OWI?

Thank you in advance.

**Comment by andybega** [comment]
You're welcome.

> What is the difference between OWA and OWI?

Sorry, I don't understand the question. What's the context for this?

**Comment by Joelmamarques** [comment]
I'm sorry Andy.
In the FFORMA paper, the author shows the OWA (overall weighted average) as the Forecast loss measure. But, in the 'Forecasting Metalearning Example' on GitHub, they use the OWI error to measure the performance. I just would like to know if the errors has the same meaning, but I don't know if you can help me with this question.

Anyway, thank you for your time.

**Comment by andybega** [comment]
Hi, yeah. I'm not affiliated in any way with the model/package authors, and have no idea. I see that you opened an issue asking them though, hope you get an answer there.
